image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_TEST_SDK: "21"
  ANDROID_SDK_TOOLS: "4333796" # 26.1.1
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GOOGLE_PUBLISH_JSON: app/misc/android-publisher-account.json


before_script:
  - apt-get --quiet update --yes
  - wget --quiet --output-document=android-sdk-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -q android-sdk-linux.zip -d android-sdk-linux
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "platforms;android-${ANDROID_COMPILE_SDK}" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "platform-tools" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "extras;android;m2repository" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "extras;google;m2repository" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "ndk-bundle" &> /dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export NDK_HOME=$ANDROID_HOME/ndk-bundle
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools
  - export GRADLE_USER_HOME=$PWD/.gradle
  - chmod +x ./gradlew


cache:
  paths:
    # gradle cache
    - .gradle/caches/
    - .gradle/wrapper/
    # rust compiled deps
    - html2md/target


.install_rust_toolchain: &install_rust_toolchain |
  apt-get --quiet install gcc --yes
  curl -sSf https://sh.rustup.rs | sh -s -- -y
  source $HOME/.cargo/env
  rustup target add armv7-linux-androideabi
  rustup target add aarch64-linux-android
  rustup target add i686-linux-android
  rustup target add x86_64-linux-android


.compile_html2md: &compile_html2md |
  cd $CI_PROJECT_DIR
  ./html2md-build.sh


.decrypt_release_account: &decrypt_publish_json |
  apt-get --quiet install gnupg2 --yes
  gpg --batch --decrypt --output ${GOOGLE_PUBLISH_JSON} --passphrase ${GOOGLE_ACCOUNT_DECRYPTION_KEY} ${GOOGLE_PUBLISH_JSON}.gpg

stages:
  - build
  - test
  - release

smoke-build:
  stage: build
  script:
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew assembleRelease

functional-tests:
  stage: test
  only:
    - web
  script:
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | android-sdk-linux/tools/bin/sdkmanager --install "system-images;android-${ANDROID_TEST_SDK};default;x86" &> /dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --install "emulator" &> /dev/null
    - echo no | android-sdk-linux/tools/bin/avdmanager create avd --name test --package "system-images;android-${ANDROID_TEST_SDK};default;x86"
    - android-sdk-linux/tools/emulator -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0
    - adb shell settings put global transition_animation_scale 0
    - adb shell settings put global animator_duration_scale 0
    - adb shell input keyevent 82
    - ./gradlew cAT

release-alpha:
  stage: release
  except:
    - merge_requests
    - tags
  script:
    - *decrypt_publish_json
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew app:publishGoogleplayRelease
  after_script:
    - rm -f ${GOOGLE_PUBLISH_JSON}
  artifacts:
    paths:
      - app/build/outputs/apk

release-gold:
  stage: release
  except:
    - merge_requests
  only:
    - tags
  script:
    - *decrypt_publish_json
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew publishGoogleplayRelease -PreleaseType=production
  after_script:
    - rm -f ${GOOGLE_PUBLISH_JSON}
  artifacts:
    paths:
      - app/build/outputs/apk
